name: TestWorkflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "*.sh"
      - "Dockerfile"
      - ".devcontainer/*"

jobs:
  test:
    container:
      image: golang:1.19.4-bullseye
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go test ./... -cover -coverprofile ./coverage.out
      - run: go tool cover -func ./coverage.out | tail -1